server:
  port: 9191


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AGENT-SERVICE
          uri: https://ensa-agentapp.herokuapp.com
          predicates:
            - Path=/api_agent/**
        - id: TRANSFER-SERVICE
          uri: https://ensa-transferapp.herokuapp.com
          predicates:
            - Path=/api_transfer/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
          cors-configurations:
             '[/**]':
             allowed-origins: "*"
             allowed-methods: "*"
             allowed-headers: "*"
             allow-credentials: true
    config:
      server:
        git:
          uri: https://github.com/houssam802/national_transfer_config_server
          default-label: main
          clone-on-start: true
          force-pull: true
          searchPaths: myapp


eureka:
  client:
    serviceUrl:
      defaultZone: https://ensaregistry-serv.herokuapp.com/eureka
  instance:
    preferIpAddress: true
