server:
  port: 9191


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: AGENT-SERVICE
          uri: https://ensa-agentapp.herokuapp.com
          predicates:
            - Path=/api_agent/**
        - id: TRANSFER-SERVICE
          uri: https://ensa-transferapp.herokuapp.com
          predicates:
            - Path=/api_transfer/**
    config:
      server:
        git:
          uri: https://github.com/houssam802/national_transfer_config_server
          default-label: main
          clone-on-start: true
          force-pull: true
          searchPaths: myapp


eureka:
  client:
    serviceUrl:
      defaultZone: https://ensaregistry-serv.herokuapp.com/eureka
  instance:
    preferIpAddress: true